# fly.toml app configuration file generated for nft-server on 2023-07-25T14:19:23+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nft-server"
primary_region = "syd"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
